import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import ReportEmbargoButton from "./ReportEmbargoButton";
import styles from "./landing.module.css";

const githubUrl = "https://github.com/mqp-dashboard-lemurs-2025-2026/lemurs-radar";

export const metadata: Metadata = {
  title: "LEMURS RADAR Project Page",
  description: "Landing page for the LEMURS RADAR WPI MQP project.",
};

// This exists to provide a more detailed landing page for the project, with links to the demo, report, and GitHub repo, as well as team member information and screenshots of the final product. 
// The main dashboard is the project itself, this is just a page for information about the project

export default function LandingPage() {
  return (
    <main className={styles.page}>
      <div className={styles.backgroundGlow} aria-hidden />

      <header className={styles.topBar}>
        <Link href="/landing" className={styles.brand}>
          <span className={styles.logoFrame}>
            <Image
              src="/LEMURS_Logo.png"
              alt="LEMURS RADAR logo"
              width={130}
              height={130}
              priority
              className={styles.logoImage}
            />
          </span>
          <span
            style={{
              color: "var(--teal-primary)",
              fontSize: "clamp(1rem, 3.2vw, 1.55rem)",
              fontWeight: 700,
              letterSpacing: "0.06em",
            }}
          >
            LEMURS RADAR
          </span>
        </Link>

        <nav className={styles.quickActions} aria-label="Quick actions">
          <Link
            href="/"
            className={`${styles.quickAction} ${styles.quickActionPrimary}`}
          >
            Dashboard Demo
          </Link>
          <a
            href={githubUrl}
            target="_blank"
            rel="noopener noreferrer"
            className={styles.quickAction}
          >
            GitHub
          </a>
          <ReportEmbargoButton className={styles.quickAction}>
            Report
          </ReportEmbargoButton>
        </nav>
      </header>

      <section className={styles.section} style={{ marginBottom: "26px" }}>
        <div className={styles.heroContent}>
          <p
            style={{
              margin: 0,
              color: "var(--teal-support)",
              textTransform: "uppercase",
              letterSpacing: "0.09em",
              fontSize: "0.84rem",
              fontWeight: 700,
            }}
          >
            WPI Major Qualifying Project
          </p>
          <h1
            style={{
              margin: "14px 0 14px",
              color: "var(--teal-primary)",
              fontSize: "clamp(1.55rem, 5.2vw, 3rem)",
              lineHeight: 1.06,
            }}
          >
            LEMURS RADAR: 
          </h1>
          <h2
            style={{
              margin: "0 0 14px",
              color: "var(--teal-support)",
              fontSize: "clamp(1.05rem, 4.2vw, 2.2rem)",
              lineHeight: 1.15,
              fontWeight: 700,
            }}
          >
            Interactive Dashboard for Risk Alerting of College Students
          </h2>
          <p
            style={{
              margin: 0,
              color: "var(--text-secondary)",
              lineHeight: 1.72,
              fontSize: "1rem",
            }}
          >
            In collaboration with experts at the Clinical Affective Science Lab (CASL) at UMASS Amherst, we have iteratively designed, developed, and evaluated an interactive visual dashboard to support medical staff in monitoring risk alerts about serious mental distress by students needing potential support.    
          </p>
        </div>
      </section>

      <section className={styles.section} style={{ marginBottom: "26px" }}>
        <div className={styles.ctaRow}>
          <Link href="/" className={`${styles.ctaButton} ${styles.primaryCta}`}>
            Live Dashboard Demo
          </Link>
          <a
            href={githubUrl}
            target="_blank"
            rel="noopener noreferrer"
            className={styles.ctaButton}
          >
            LEMURS RADAR GitHub
          </a>
          <ReportEmbargoButton className={styles.ctaButton}>
            WPI MQP Report
          </ReportEmbargoButton>
        </div>
        <p className={styles.demoDisclaimer}>
          The dashboard demo uses synthetic student records generated by our data creation
          program.
        </p>
      </section>

      <section
        className={styles.section}
        id="team"
        style={{ marginBottom: "26px" }}
      >
        <div className={styles.sectionHeader}>
          <h2
            style={{
              margin: 0,
              fontSize: "clamp(1.2rem, 4vw, 1.8rem)",
              color: "var(--teal-primary)",
            }}
          >
            Meet the Team
          </h2> 
          <p style={{ margin: "8px 0 0", color: "var(--text-secondary)" }}>
            LEMURS Radar Project Team Members and Contributions
          </p>
        </div>

        <div className={styles.teamGrid}>
          <article className={styles.teamCard}>
            <Image
              src="/team_photos/skyler.jpg"
              alt="Skyler Dooley"
              width={96}
              height={96}
              style={{
                margin: "0 auto 12px",
                borderRadius: "50%",
                border: "3px solid var(--teal-accent)",
                background: "#ffffff",
                objectFit: "cover",
              }}
            />
            <h3
              style={{
                margin: 0,
                fontSize: "1.04rem",
                color: "var(--teal-primary)",
              }}
            >
              <a
                href="https://www.linkedin.com/in/skyler-d-42b7a7259/"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "inherit", textDecoration: "none" }}
              >
                Skyler Dooley
              </a>
            </h3>
            <p
              style={{
                margin: "6px 0 0",
                color: "var(--text-secondary)",
                fontSize: "0.82rem",
                fontWeight: 600,
              }}
            >
              CS/DS
            </p>
            <details className={styles.contributionDetails}>
              <summary>Contributions</summary>
              <p>
                Skyler contributed primarily to project organization and team coordination throughout the development process. She also served as the main point of contact for communication with project advisors and clinicians, coordinating emails and scheduling interviews. In addition, she contributed to the early design sketches of the clinician-facing dashboard and worked on the front-end implementation, including the hover-based risk trend chart on the main page.
              </p>
            </details>
          </article>

          <article className={styles.teamCard}>
            <Image
              src="/team_photos/jeffrey.jpg"
              alt="Jeffrey Li profile"
              width={96}
              height={96}
              style={{
                margin: "0 auto 12px",
                borderRadius: "50%",
                border: "3px solid var(--teal-accent)",
                background: "#ffffff",
                objectFit: "cover",
              }}
            />
            <h3
              style={{
                margin: 0,
                fontSize: "1.04rem",
                color: "var(--teal-primary)",
              }}
            >
              <a
                href="https://www.linkedin.com/in/jeffrey-li-156013203/"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "inherit", textDecoration: "none" }}
              >
                Jeffrey Li
              </a>
            </h3>
            <p
              style={{
                margin: "6px 0 0",
                color: "var(--text-secondary)",
                fontSize: "0.82rem",
                fontWeight: 600,
              }}
            >
              CS
            </p>
            <details className={styles.contributionDetails}>
              <summary>Contributions</summary>
              <p>
                Jeffrey contributed primarily to the development of the clinician-facing dashboard. He implemented the main dashboard page for the first iteration of the dashboard as well as the display and design of the revised dashboard individual student page, in addition to various debugging tasks throughout the application. It should be noted that Jeffrey was registered for half the credit load during the second semester of the project.
              </p>
            </details>
          </article>

          <article className={styles.teamCard}>
            <Image
              src="/team_photos/dan.png"
              alt="Daniel Mastrobuono"
              width={96}
              height={96}
              style={{
                margin: "0 auto 12px",
                borderRadius: "50%",
                border: "3px solid var(--teal-accent)",
                background: "#ffffff",
                objectFit: "cover",
              }}
            />
            <h3
              style={{
                margin: 0,
                fontSize: "1.04rem",
                color: "var(--teal-primary)",
              }}
            >
              <a
                href="https://www.linkedin.com/in/daniel-mastrobuono-953115276/"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "inherit", textDecoration: "none" }}
              >
                Daniel Mastrobuono
              </a>
            </h3>
            <p
              style={{
                margin: "6px 0 0",
                color: "var(--text-secondary)",
                fontSize: "0.82rem",
                fontWeight: 600,
              }}
            >
              CS
            </p>
            <details className={styles.contributionDetails}>
              <summary>Contributions</summary>
              <p>
                Dan contributed primarily to graph displays across both the first iteration of the dashboard and the second. In the research-facing dashboard, Dan focused on the heatmap. In the clinician-facing dashboard, Dan produced the multitude of graphs that appear on the individual student page. Also contributed to general bug fixes along the way. Dan led all the clinician interviews, and focused on those sections of the paper as well, along with the introduction to the report. 
              </p>
            </details>
          </article>

          <article className={styles.teamCard}>
            <Image
              src="/team_photos/nixon.jpg"
              alt="Nixon Showalter"
              width={96}
              height={96}
              style={{
                margin: "0 auto 12px",
                borderRadius: "50%",
                border: "3px solid var(--teal-accent)",
                background: "#ffffff",
                objectFit: "cover",
              }}
            />
            <h3
              style={{
                margin: 0,
                fontSize: "1.04rem",
                color: "var(--teal-primary)",
              }}
            >
              <a
                href="https://www.linkedin.com/in/nixonshowalter/"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "inherit", textDecoration: "none" }}
              >
                Nixon Showalter
              </a>
            </h3>
            <p
              style={{
                margin: "6px 0 0",
                color: "var(--text-secondary)",
                fontSize: "0.82rem",
                fontWeight: 600,
              }}
            >
              CS/DS
            </p>
            <details className={styles.contributionDetails}>
              <summary>Contributions</summary>
              <p>
                Nixon served as the Project Lead and oversaw the technical implementation of the LEMURS RADAR dashboard. He contributed to the full stack development of both the researcher-facing and clinician-facing dashboards, with a focus on user data management and display. His work included the development of data generation tools, the implementation of the student display page and visualizations, and the design and iteration of initial sketches for the clinician-facing dashboard. He also completed additional implementation, testing, and debugging tasks required to finalize the system and project deliverables.
              </p>
            </details>
          </article>

          <article className={styles.teamCard}>
            <Image
              src="/team_photos/willem.jpg"
              alt="Willem van Oosterum"
              width={96}
              height={96}
              style={{
                margin: "0 auto 12px",
                borderRadius: "50%",
                border: "3px solid var(--teal-accent)",
                background: "#ffffff",
                objectFit: "cover",
              }}
            />
            <h3
              style={{
                margin: 0,
                fontSize: "1.04rem",
                color: "var(--teal-primary)",
              }}
            >
              <a
                href="https://www.linkedin.com/in/willem-van-oosterum/"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "inherit", textDecoration: "none" }}
              >
                Willem van Oosterum
              </a>
            </h3>
            <p
              style={{
                margin: "6px 0 0",
                color: "var(--text-secondary)",
                fontSize: "0.82rem",
                fontWeight: 600,
              }}
            >
              CS
            </p>
            <details className={styles.contributionDetails}>
              <summary>Contributions</summary>
              <p>
                Willem contributed primarily to the main dashboard page development, as well as deployment to development and production servers. On the main dashboard, he designed and implemented the student information tiles, filters, and search functionality. He also led the initial containerization and deployment of the project, using Docker and WPI servers to host the project and its services. It should be noted that Willem was registered for half the credit load during the second semester of the project.
              </p>
            </details>
          </article>
        </div>
      </section>

      <section
        className={styles.section}
        id="screenshots"
        style={{ marginBottom: "26px" }}
      >
        <div className={styles.sectionHeader}>
          <h2
            style={{
              margin: 0,
              fontSize: "clamp(1.2rem, 4vw, 1.8rem)",
              color: "var(--teal-primary)",
            }}
          >
            Final Product Screenshots
          </h2>
          <p style={{ margin: "8px 0 0", color: "var(--text-secondary)" }}>
            LEMURS Radar Dashboard Screenshots and Project Poster
          </p>
        </div>

        <div className={styles.screenshotGrid}>
          <figure className={styles.screenshotCard}>
            <div
              className={styles.browserFrame}
              role="img"
              aria-label="Main dashboard screenshot"
            >
              <div className={styles.browserBar}>
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ff7d7d",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ffd56c",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#69c795",
                  }}
                />
              </div>
              <div className={styles.screenshotMedia}>
                <Image
                  src="/deliverables/main_dashboard.png"
                  alt="Main dashboard screenshot"
                  fill
                  sizes="(max-width: 640px) 100vw, 50vw"
                  className={styles.screenshotImage}
                />
              </div>
            </div>
            <figcaption
              style={{
                padding: "12px 14px 14px",
                color: "var(--text-secondary)",
                lineHeight: 1.45,
              }}
            >
              LEMURS RADAR Main Dashboard
            </figcaption>
          </figure>

          <figure className={styles.screenshotCard}>
            <div
              className={styles.browserFrame}
              role="img"
              aria-label="Individual student screenshot"
            >
              <div className={styles.browserBar}>
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ff7d7d",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ffd56c",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#69c795",
                  }}
                />
              </div>
              <div className={styles.screenshotMedia}>
                <Image
                  src="/deliverables/indv_student.png"
                  alt="Individual student screenshot"
                  fill
                  sizes="(max-width: 640px) 100vw, 50vw"
                  className={styles.screenshotImage}
                />
              </div>
            </div>
            <figcaption
              style={{
                padding: "12px 14px 14px",
                color: "var(--text-secondary)",
                lineHeight: 1.45,
              }}
            >
              LEMURS RADAR Individual Student Display
            </figcaption>
          </figure>

          <figure className={`${styles.screenshotCard} ${styles.posterCard}`}>
            <div className={styles.browserFrame}>
              <div className={styles.browserBar}>
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ff7d7d",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#ffd56c",
                  }}
                />
                <span
                  style={{
                    width: 10,
                    height: 10,
                    borderRadius: "50%",
                    background: "#69c795",
                  }}
                />
              </div>
              <div className={styles.posterPanel}>
                <iframe
                  src="/deliverables/poster.pdf#view=FitH"
                  title="Project poster PDF preview"
                  className={styles.posterEmbed}
                />
              </div>
            </div>
            <figcaption
              style={{
                padding: "12px 14px 14px",
                color: "var(--text-secondary)",
                lineHeight: 1.45,
              }}
            >
              LEMURS RADAR Project Poster{" "}
              <a
                href="/deliverables/poster.pdf"
                target="_blank"
                rel="noopener noreferrer"
                className={styles.posterLink}
              >
                Open PDF
              </a>
            </figcaption>
          </figure>
        </div>
      </section>

      <section
        className={styles.section}
        id="acknowledgements"
        style={{ marginBottom: "26px" }}
      >
        <div className={styles.heroPanel}>
          <h2
            style={{
              margin: "0 0 10px",
              fontSize: "1.15rem",
              color: "var(--teal-primary)",
            }}
          >
            Acknowledgements
          </h2>
          <p
            style={{
              margin: 0,
              color: "var(--text-secondary)",
              lineHeight: 1.65,
            }}
          >
            We would like to sincerely thank Professor Elke Rundensteiner, who is a professor in Computer Science, Data Science and Artificial Intelligence at WPI, for providing the opportunity to work on this project and her sustained guidance in the direction of the project.
            <br />
            We appreciate the assistance of the rest of the WPI LEMURS RADAR project team, namely, the PhD students - Kevin Hickey, Dennis Hofmann, Avantika Shrestha, and Peter VanNostrand - for helping with various external dependencies, providing input on the functionality and intended usage of the technology in the context of the LEMURS RADAR project.
          </p>
        </div>
      </section>

      <footer className={styles.footer}>
        <p
          style={{
            margin: 0,
            color: "var(--teal-primary)",
            fontWeight: 700,
          }}
        >
          LEMURS RADAR
        </p>
        <div className={styles.footerLinks}>
          <Link href="/">Live Dashboard Demo</Link>
          <a>-</a>
          <a href={githubUrl} target="_blank" rel="noopener noreferrer">
            LEMURS RADAR GitHub
          </a>
          <a>-</a>
          <ReportEmbargoButton className={styles.footerReportButton}>
            WPI MQP Report
          </ReportEmbargoButton>
        </div>
      </footer>
    </main>
  );
}
